### ISSUE TITLE
Can't Compile

### ISSUE THREAD

**Issue by DaxSosa** [zxystd/AthBluetoothFirmware#1]
MacBook-Pro:AthBluetoothFirmware daxsosa$ ./fw_gen.sh 
./fw_gen.sh: line 19: /AthBluetoothFirmware/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 20: /AthBluetoothFirmware/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 34: /AthBluetoothFirmware/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 36: /AthBluetoothFirmware/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 45: /AthBluetoothFirmware/FwBinary.cpp: No such file or directory
./fw_gen.sh: line 46: /AthBluetoothFirmware/FwBinary.cpp: No such file or directory

**Comment by zxystd** [comment]
I had publish the release, you can download there, thanks.

**Comment by DaxSosa** [comment]
the system crash my friend , I work in mojave 10.14.1, make a boot loop

**Comment by zxystd** [comment]
@DaxSosa any kp logs? it is test well.

**Comment by DaxSosa** [comment]
I managed to compile the files but with the kextload command it does not load the kext in the kernel, and when I installed the release that you made, I could not boot the machine, I am going to check the xcode logs

**Comment by DaxSosa** [comment]
@zxystd I managed to compile it, but neither the kext in debug or release works, the kernel does not load them, I changed the release type for my version of mac os, and the release version you published crashes the system, so I have to delete the kext from linux

**Comment by shaizu** [comment]
true it crashes my system also
can't even boot

**Comment by zxystd** [comment]
show the crash log, or your feedback will be nonsense.

**Comment by shaizu** [comment]
https://imgur.com/j5YQndU

> show the crash log, or your feedback will be nonsense.

**Comment by zxystd** [comment]
@shaizu can't open the link, should upload here.

**Comment by shaizu** [comment]
> @shaizu can't open the link, should upload here.

![j5YQndU](https://user-images.githubusercontent.com/30232599/93889584-fdecb100-fd06-11ea-81e3-829a11f279dc.jpeg)

**Comment by sarthakaditya52** [comment]
Any workaround yet ? I'm also unable to boot with the kexts injected in OC

**Comment by whatnameisit** [comment]
[opencore-2020-10-12-135846.txt](https://github.com/zxystd/AthBluetoothFirmware/files/5365569/opencore-2020-10-12-135846.txt)

**Comment by htpcrig** [comment]
Any update on this. Im having the exact issue too
