### ISSUE TITLE
Can't boot in Monterey 

### ISSUE THREAD

**Issue by abdosoft13** [zxystd/AthBluetoothFirmware#11]
I add the kexts in the opencore v0.9.7 Kexts's folder and activate them in the config.plist, then rebooted, but I'm stuck in a black screen with no helpful information to provide, and can't find the log of the boot, only the last boot is present.

is those files still works on Monterey ?

**Comment by zxystd** [comment]
It may work, but you need to pay attention to the following things.
- Avoid using `Ath3kBTInjector.kext`, just replace with https://github.com/acidanthera/BrcmPatchRAM/releases `BluetoolFixup.kext` since Monterey and later macOS changes the bluetooth drivers a lot.

**Comment by abdosoft13** [comment]
Same behavior after the changes you suggested, I have now a message says that the panic occurred prior to initialization.

![WhatsApp Image 2024-01-29 at 23 39 41](https://github.com/zxystd/AthBluetoothFirmware/assets/157969397/84870703-15ad-4125-8414-bb133a8bd9e5)

**Comment by zxystd** [comment]
The panic is not caused by this driver.
