### ISSUE TITLE
support for bluetooth Atheros with Device ID 0xE007

### ISSUE THREAD

**Issue by jonasw8** [zxystd/AthBluetoothFirmware#4]
Hi!
I have a Dell 5557 with Wifi QCA 6174 and bluetooh 0xE007

I edited info.plist of Ath3kBT.kext and Ath3kBTInjector.kext but not work

Its possible add support for this model?

Thx
![Captura de Tela 1400-02-28 às 01 19 07](https://user-images.githubusercontent.com/53247355/119252300-d6920080-bb81-11eb-841b-aacadfa539e5.png)

**Comment by zxystd** [comment]
It is possible, but I don't have QCA device to test... it is the trouble.

**Comment by zxystd** [comment]
Close since it is inactive.
