### ISSUE TITLE
Can work below 10.12?

### ISSUE THREAD

**Issue by htpcrig** [zxystd/AthBluetoothFirmware#6]
Can this work below 10.12 if i compile it, like 10.11?

**Comment by zxystd** [comment]
It can work on 10.11 in theory but not below because USB stack change a lot below 10.11 version.

**Comment by ellaosx2007** [comment]
Hi again @zxystd 
I managed to compile for 10.11 (ElCap). The binary size went up to 941KB while yours is 409KB. Is it OK?
