### ISSUE TITLE
启动的时候比较慢，一直显示Ath3kBt::message

### ISSUE THREAD

**Issue by yipanbo** [zxystd/AthBluetoothFirmware#9]
大佬，麻烦问下我的黑苹果蓝牙是qualcomm qca9565，用了这个驱动，可以开机，可以使用蓝牙，只是在启动的时候，一直显示Ath3kBt::message，而且启动特别慢，这个是什么问题？能解决一下么？谢谢！

**Comment by zxystd** [comment]
禁用了这个驱动速度就快了？USB定制了么？
